name: ReleaseMusl

on:
  workflow_dispatch:

jobs:
  test-foundryup-windows:
    runs-on: windows-latest

    steps:
      - name: Set up Windows Environment
        shell: bash
        run: |
          echo "Setting up Windows environment..."
          echo "RUNNER_OS=${RUNNER_OS}"
          echo "USERPROFILE=$USERPROFILE"
          echo "PATH=$PATH"

      - name: Install Foundryup
        shell: bash
        run: |
          echo "Downloading foundryup installer..."
          curl -L https://raw.githubusercontent.com/soul022/foundry-revive-testing/refs/heads/master/foundryup/install -o foundryup-install.sh
          
          chmod +x foundryup-install.sh
          ./foundryup-install.sh || echo "⚠️ Foundryup installation failed!"

      - name: Extract and Verify Binaries
        shell: bash
        run: |
          echo "Extracting Foundry binaries..."
          FOUNDARY_BIN_PATH="/c/Users/runneradmin/.config/foundry/bin"
          mkdir -p "$FOUNDARY_BIN_PATH"

          # Extract binaries
          unzip -o foundry_stable_win32_amd64.zip -d "$FOUNDARY_BIN_PATH"

          # Ensure correct permissions
          chmod +x "$FOUNDARY_BIN_PATH/forge.exe"
          chmod +x "$FOUNDARY_BIN_PATH/cast.exe"

          # Add to PATH
          echo "Adding Foundryup binaries to PATH: $FOUNDARY_BIN_PATH"
          echo "$FOUNDARY_BIN_PATH" >> $GITHUB_PATH
          export PATH="$FOUNDARY_BIN_PATH:$PATH"

          # Debugging output
          echo "Listing extracted files..."
          ls -lah "$FOUNDARY_BIN_PATH"

      - name: Verify Foundryup Installation
        shell: bash
        run: |
          echo "🖥️ System Info"
          uname -s
          uname -m

          echo "Checking Foundryup installation..."
          which foundryup || echo "⚠️ foundryup command not found"
          where.exe forge || echo "⚠️ forge binary not found in PATH"
          where.exe cast || echo "⚠️ cast binary not found in PATH"

          echo "Running Foundryup installation..."
          foundryup --install stable || echo "⚠️ Foundryup installation failed!"

          echo "Checking installed versions..."
          forge --version && echo "✅ forge is working!" || echo "❌ forge command not available after install"
          cast --version && echo "✅ cast is working!" || echo "❌ cast command not available after install"

          echo "🔍 Running sanity test for forge and cast..."
          "$FOUNDARY_BIN_PATH/forge.exe" --help && echo "✅ forge.exe runs correctly!"
          "$FOUNDARY_BIN_PATH/cast.exe" --help && echo "✅ cast.exe runs correctly!"
