name: ReleaseMusl

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  test-foundryup-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Foundryup Installation (Windows)
        shell: bash
        run: |
          echo "=== Windows OS Detection ==="
          uname -s
          uname -m
          
          echo "=== Downloading Foundryup ==="
          curl -L https://raw.githubusercontent.com/soul022/foundry-revive-testing/refs/heads/master/foundryup/install | bash

          echo "=== Setting Foundry PATH ==="
          export FOUNDARY_BIN_PATH="$USERPROFILE/.foundry/bin"
          export PATH="$FOUNDARY_BIN_PATH:$PATH"
          echo "$FOUNDARY_BIN_PATH" >> $GITHUB_PATH
          
          echo "=== Debug: Checking Installation Directory ==="
          ls -lah "$FOUNDARY_BIN_PATH" || echo "❌ Foundry binaries directory not found!"

          echo "=== Running Foundryup ==="
          foundryup --install "stable" || echo "⚠️ Foundryup installation failed!"

          echo "=== Verifying Forge & Cast Installation ==="
          which forge || echo "❌ forge binary not found in PATH"
          which cast || echo "❌ cast binary not found in PATH"

          echo "=== Checking Forge & Cast Versions ==="
          forge --version || echo "❌ forge command not available after install"
          cast --version || echo "❌ cast command not available after install"
