name: ReleaseMusl

on:
  workflow_dispatch:

jobs:
  test-foundryup-windows:
    runs-on: windows-latest

    steps:
      - name: Set up Windows Environment
        shell: powershell
        run: |
          echo "Setting up Windows environment..."
          echo "RUNNER_OS=${env:RUNNER_OS}"
          echo "USERPROFILE=$env:USERPROFILE"
          echo "PATH=$env:PATH"

      - name: Install Foundryup
        shell: powershell
        run: |
          echo "Downloading foundryup installer..."
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/soul022/foundry-revive-testing/refs/heads/master/foundryup/install" -OutFile "foundryup-install.ps1"

          # Run the installer
          powershell -ExecutionPolicy Bypass -File .\foundryup-install.ps1
          
          # Find the installation path
          $FoundryPath = "C:\Users\runneradmin\.config\foundry\bin"
          
          # Add Foundryup to PATH
          [System.Environment]::SetEnvironmentVariable("Path", $env:Path + ";$FoundryPath", [System.EnvironmentVariableTarget]::User)
          $env:PATH += ";$FoundryPath"
          echo "$FoundryPath" >> $GITHUB_PATH

      - name: Verify Foundryup Installation
        shell: powershell
        run: |
          # Find foundryup binary
          Get-ChildItem -Recurse -Path "C:\Users\runneradmin" -Filter "foundryup*" -ErrorAction SilentlyContinue

          # Verify installation
          $FoundryPath = "C:\Users\runneradmin\.config\foundry\bin"

          if (!(Test-Path "$FoundryPath\foundryup.exe")) {
            echo "⚠️ foundryup command not found!"
            exit 1
          }

          # Install Foundry
          & "$FoundryPath\foundryup.exe" --install stable

          # Verify forge and cast installation
          if (!(Test-Path "$FoundryPath\forge.exe")) {
            echo "⚠️ forge command not found!"
            exit 1
          }

          if (!(Test-Path "$FoundryPath\cast.exe")) {
            echo "⚠️ cast command not found!"
            exit 1
          }

          # Run versions
          & "$FoundryPath\forge.exe" --version
          & "$FoundryPath\cast.exe" --version
