name: ReleaseMusl

on:
  workflow_dispatch:

jobs:
  test-foundryup-windows:
    runs-on: windows-latest

    steps:
      - name: Set up Windows Environment
        shell: bash
        run: |
          echo "Setting up Windows environment..."
          echo "RUNNER_OS=${RUNNER_OS}"
          echo "USERPROFILE=$USERPROFILE"
          echo "PATH=$PATH"

      - name: Install Foundryup
        shell: bash
        run: |
          echo "Downloading foundryup installer..."
          curl -L https://raw.githubusercontent.com/soul022/foundry-revive-testing/refs/heads/master/foundryup/install -o foundryup-install.sh
          
          chmod +x foundryup-install.sh
          ./foundryup-install.sh || echo "⚠️ Foundryup installation failed!"

          # Ensure foundryup path is added
          FOUNDY_PATH="/c/Users/runneradmin/.config/foundry/bin"
          echo "Adding Foundryup to PATH: $FOUNDY_PATH"
          echo "$FOUNDY_PATH" >> $GITHUB_PATH
          export PATH="$FOUNDY_PATH:$PATH"

      - name: Verify Foundryup Installation
        shell: bash
        run: |
          # Debug system details
          echo "🖥️ System Info"
          uname -s
          uname -m
          
          echo "Checking Foundryup installation..."
          which foundryup || echo "⚠️ foundryup command not found"
          which forge || echo "⚠️ forge binary not found in PATH"
          which cast || echo "⚠️ cast binary not found in PATH"

          echo "Running Foundryup installation..."
          foundryup --install stable || echo "⚠️ Foundryup installation failed!"

          echo "Checking installed versions..."
          forge --version || echo "⚠️ forge command not available after install"
          cast --version || echo "⚠️ cast command not available after install"
